# Generated by Django 6.0.5 on 2026-05-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0002_credit_supplier_suppliercredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.IntegerField()),
                ('cost_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
