# Generated by Django 6.0.5 on 2026-05-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0003_transportcharge_alter_user_nin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
