# Generated by Django 6.0.5 on 2026-05-31 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('cement', 'Cement'), ('iron_bar', 'Iron Bar'), ('iron_sheets', 'Iron Sheets'), ('nails', 'Nails'), ('paint', 'Paint')], max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_required', models.BooleanField(default=False)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('nin_number', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('occupation', models.CharField(default='Salary Earner', max_length=100)),
                ('employer_name', models.CharField(blank=True, max_length=150)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeGoodsPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_taken', models.PositiveIntegerField()),
                ('pickup_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.schemecustomer')),
                ('linked_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nyondo_app.sales')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='SchemePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.schemecustomer')),
            ],
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.DeleteModel(
            name='DepositScheme',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='suppliercredit',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='TransportCharge',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='created_at',
            new_name='date_received',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='mode_of_payment',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product_specifications',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unit',
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='supplier_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='supplier_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='StockTransaction',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierCredit',
        ),
    ]
