# Generated by Django 6.0.5 on 2026-06-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0005_product_sales_schemecustomer_schemegoodspickup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(choices=[('cement', 'Cement'), ('iron_bar', 'Iron Bar'), ('iron_sheets', 'Iron Sheets'), ('others', 'Others'), ('nails', 'Nails'), ('paint', 'Paint')], max_length=20),
        ),
    ]
